version: '2'

services:
    coston:
      image: flarefoundation/flare:latest
      ports:
        - '9650:9650'
        - '9651:9651'
      environment:
        - BOOTSTRAP_IPS=$$(curl -m 10 -sX POST --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeIP" }' -H 'content-type:application/json;' https://coston.flare.network/ext/info | jq -r ".result.ip") \
        - BOOTSTRAP_IDS=$$(curl -m 10 -sX POST --data '{ "jsonrpc":"2.0", "id":1, "method":"info.getNodeID" }' -H 'content-type:application/json;' https://coston.flare.network/ext/info | jq -r ".result.nodeID") \
        - NETWORK_ID="coston"
        - DB_DIR="/data/db"
        - DB_TYPE"leveldb"
        - HTTP_HOST=0.0.0.0
        - HTTP_PORT=9650
        - LOG_DIR="/data/logs"
        - LOG_DISPLAY_LEVEL="info"
        - LOG_LEVEL="info"
